/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 eagle.gltf --transform
Author: dinomaster (https://sketchfab.com/dinomaster)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/my-animated-eagle-40dd320d0e2342ae9ae9343d4f90c09b
Title: my animated eagle
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/eagle-transformed.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Flap"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={2}>
          <group name="Flapfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Eagle" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Eagle(0)">
                    <group
                      name="Bip01"
                      position={[0, 0, 28.81]}
                      rotation={[-0.04, 0, -Math.PI / 2]}
                    >
                      <group name="Object_7">
                        <primitive object={nodes._rootJoint} />
                        <skinnedMesh
                          name="Object_95"
                          geometry={nodes.Object_95.geometry}
                          material={materials.lambert4SG}
                          skeleton={nodes.Object_95.skeleton}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/eagle-transformed.glb");
